<?php

/**
 * Module file for the Past DB module.
 */

/**
 * Implements hook_entity_info()
 */
function past_db_entity_info() {
  $info['past_event'] = array(
    'label' => t('Past Event'),
    'module' => 'past_db',
    'controller class' => 'PastEventController',
    'metadata controller class' => 'PastDBEventMetadataController',
    'views controller class' => 'PastDBEventViewsController',
    'entity class' => 'PastEvent',
    'base table' => 'past_event',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'access callback' => 'past_db_event_access',
    'entity keys' => array(
      'id' => 'event_id',
    ),
  );

  $info['past_event_argument'] = array(
    'label' => t('Past Event Argument'),
    'module' => 'past_db',
    'controller class' => 'PastEventArgumentController',
    'metadata controller class' => 'PastDBEventMetadataController',
    //'views controller class' => 'PastDBEventViewsController',
    'entity class' => 'PastEventArgument',
    'base table' => 'past_event_argument',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'access callback' => 'past_db_event_argument_access',
    'entity keys' => array(
      'id' => 'argument_id',
    ),
  );

  return $info;
}

/**
 * Implements hook_permission().
 */
function past_db_permission() {
  return array(
    'administer past db' => array(
      'title' => t('Administer Past DB'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function past_db_menu() {
  $items['admin/config/past/settings'] = array(
    'title' => 'Past settings',
    'description' => 'Configure relevance settings for search and other indexing options.', // @todo fix
    'page callback' => 'drupal_get_form',
    'page arguments' => array('past_admin_settings'),
    'access arguments' => array('administer past db'),
    'file' => 'past_db.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_cron().
 */
function past_db_cron() {
  // Check if expiration is enabled.
  if ($expire = variable_get('past_events_expire', 0)) {
    // Fetch up to 100 past events to delete, delete oldest first.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'past_event');
    $query->propertyCondition('timestamp', REQUEST_TIME - $expire, '<');
    $query->propertyOrderBy('timestamp');
    $query->range(0, 100);
    $result = $query->execute();
    if ($result) {
      entity_delete_multiple('past_event', array_keys($result['past_event']));
    }
  }
}

