<?php

/**
 * Module file for the Past DB module.
 */

/**
 * Implements hook_entity_info()
 */
function past_db_entity_info() {
  $info['past_event'] = array(
    'label' => t('Past Event'),
    'module' => 'past_db',
    'controller class' => 'PastEventController',
    //'metadata controller class' => 'PastDBEventMetadataController',
    //'views controller class' => 'PastDBEventViewsController',
    'entity class' => 'PastEvent',
    'base table' => 'past_event',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'access callback' => 'past_db_event_access',
    'entity keys' => array(
      'id' => 'event_id',
    ),
  );
  $info['past_event_argument'] = array(
    'label' => t('Past Event Argument'),
    'module' => 'past_db',
    'controller class' => 'PastEventArgumentController',
    //'metadata controller class' => 'PastDBEventMetadataController',
    //'views controller class' => 'PastDBEventViewsController',
    'entity class' => 'PastEventArgument',
    'base table' => 'past_event_argument',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'access callback' => 'past_db_event_argument_access',
    'entity keys' => array(
      'id' => 'argument_id',
    ),
  );
  return $info;
}