<?php

/**
 * Module file for the Past DB module.
 */

/**
 * Implements hook_entity_info()
 */
function past_db_entity_info() {
  $info['past_event'] = array(
    'label' => t('Past Event'),
    'module' => 'past_db',
    'controller class' => 'PastEventController',
    'metadata controller class' => 'PastDBEventMetadataController',
    //'views controller class' => 'PastDBEventViewsController',
    'entity class' => 'PastEvent',
    'base table' => 'past_event',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'access callback' => 'past_db_access',
    'entity keys' => array(
      'id' => 'event_id',
    ),
    'admin ui' => array(
      'controller class' => 'PastDBEventUIController',
      'path' => 'admin/reports/past',
    ),
  );

  $info['past_event_argument'] = array(
    'label' => t('Past Event Argument'),
    'module' => 'past_db',
    'controller class' => 'PastEventArgumentController',
    //'metadata controller class' => 'PastDBEventMetadataController',
    //'views controller class' => 'PastDBArgumentViewsController',
    'entity class' => 'PastEventArgument',
    'base table' => 'past_event_argument',
    'uri callback' => 'entity_class_uri',
    'label callback' => 'entity_class_label',
    'access callback' => 'past_db_access',
    'entity keys' => array(
      'id' => 'argument_id',
    ),
  );

  return $info;
}

/**
 * Access callback implementation.
 * @param $operation
 *   The performed operation - view, delete, create, update, customs...
 * @param $entity
 *   (optional) The entity on which $operation should be performed.
 * @param $account
 *   (optional) The account to check if it has access.
 * @return boolean
 *    TRUE if $account can perform $operation on $entity
 */
function past_db_access($op, $entity = NULL, $account = NULL) {
  return user_access('administer past', $account);
}

/**
 * Implements hook_cron().
 */
function past_db_cron() {
  // Check if expiration is enabled.
  if ($expire = variable_get('past_events_expire', 0)) {
    // Fetch up to 100 past events to delete, delete oldest first.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'past_event');
    $query->propertyCondition('timestamp', REQUEST_TIME - $expire, '<');
    $query->propertyOrderBy('timestamp');
    $query->range(0, 100);
    $result = $query->execute();
    if ($result) {
      entity_delete_multiple('past_event', array_keys($result['past_event']));
    }
  }
}

/**
 * Implements views arguments details.
 * defined in PastDBArgumentUIController::hook_menu().
 */
function past_db_event_view($event) {
  return entity_view($event->entityType(), array($event), 'full', NULL, TRUE);
}

/**
 * Implements hook_views_api().
 */
function past_db_views_api() {
  return array(
    'api' => 3,
  );
}
