<?php

/**
 * @file
 * Main bootstrap file for past_guzzle.
 */

use Guzzle\Plugin\Log\LogPlugin;

define('PAST_GUZZLE_SIMPLE', '\SimplePastGuzzleLogAdapter');
define('PAST_GUZZLE_COMPACT', '\CompactPastGuzzleLogAdapter');

/**
 * Gets the guzzle log plugin.
 *
 * @param string $adapter
 *   The class name of the plugin adapter used in the log plugin.
 *
 * @return Guzzle\Plugin\Log\LogPlugin
 *   An instances of a guzzle log plugin configured with the Past Guzzle
 *   adapter.
 */
function past_guzzle_plugin($adapter = PAST_GUZZLE_SIMPLE) {
  return drupal_static($adapter, new LogPlugin(new $adapter(), \PastGuzzleLogAdapter::MESSAGE_FORMAT));
}
